#define ACCESS_BITS 5
#define ACL_DIR "acls/"
#define ACL_EXT ".acl"
#define ADMIN "admin"
#define CONCAT "+"
#define DELIMITER "."
#define MAX_ACL_ENTRIES 10
#define MAX_DATA 100
#define OBJECT_DIR "objects/"
#define S_FULL "rwxpv"
#define SLASH "/"
#define SPACE " "
#define WILD_MATCH "*"
#define READ "r"
#define WRITE "w"
#define EXECUTE "x"
#define PERMIT "p"
#define VIEW "v"
#define EMPTY_STRING ""
